INSERT INTO public.skills (resume_id, skill_name) 
VALUES
    (1, 'Linux'),
    (1, 'Bash'),
    (1, 'C Programming Language'),
	(1, 'C++'),
	(1, 'C#'),
	(1, 'GoLang'),
	(1, 'React.js'),
	(1, 'HTML'),
	(1, 'CSS'),
	(1, 'Node.js'),
	(1, 'Next.js'),
	(1, 'TailWind'),
	(1, 'PostgreSQL'),
	(1, 'Redis'),
	(1, 'MSSQL'),
	(1, 'AWS'),
	(1, 'Git'),
	(1, 'RESTful APIs'),
	(1, 'PowerShell'),
	(1, 'TypeScript'),
	(1, 'Agile/Scrum'),
	(1, 'Cross-functional team collaboration'),
	(1, 'Project management tools'),
	(1, 'Jira'),
	(1, 'Trello'),
	(1, 'Confluence'),
	(1, 'Mentoring'),
	(1, 'Code Reviews'),
	(1, 'leadership');